coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
        informational: true
    patch:
      default:
        target: 60%
        threshold: 5%
        informational: true
